CREATE OR REPLACE TRIGGER TRG_VALIDATE_CONTACT_INFO
BEFORE INSERT OR UPDATE OF CONTACT_INFO ON PERSON
FOR EACH ROW
BEGIN
    IF LENGTH(:NEW.CONTACT_INFO) != 10 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Contact info must be 10 digits');
    END IF;
END;
/
INSERT INTO PERSON (PERSON_ID, NAME, CONTACT_INFO, ADDRESS) 
VALUES (214, 'Aayam', '9764238213', 'Bristol');
/
INSERT INTO PERSON (PERSON_ID, NAME, CONTACT_INFO, ADDRESS) 
VALUES (215, 'Pratham', '982125472', 'Oxford');