CREATE OR REPLACE TRIGGER TRG_PREVENT_CLOSING_WITHOUT_DATE
BEFORE UPDATE OF STATUS ON CRIME
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'SOLVED' AND :NEW.CRIME_SOLVE_DATE IS NULL THEN
        RAISE_APPLICATION_ERROR(-20005, 'CANNOT SET STATUS TO "SOLVED" WITHOUT SPECIFYING CRIME SOLVED DATE.');
    END IF;
END;
/
UPDATE CRIME
SET STATUS = 'SOLVED', CRIME_SOLVE_DATE = SYSDATE
WHERE CRIME_ID = 104;
/
UPDATE CRIME
SET STATUS = 'SOLVED'
WHERE CRIME_ID = 107;