-- CREATE VIEW Crime_Details_View AS
-- SELECT 
-- C.CRIME_ID,
-- C.NAME AS CRIME_NAME,
-- C.CRIME_DATE,
-- C.STATUS AS CRIME_STATUS,
-- L.CITY AS CRIME_LOCATION_CITY,
-- L.REGION AS CRIME_LOCATION_REGION,
-- P.NAME AS PERSON_INVOLVED,
-- CP.fk1_PERSON_ID AS PERSON_ID,
-- E.EVIDENCE_DESCRIPTION
-- FROM CRIME C
-- JOIN LOCATION L ON C.fk1_LOCATION_ID = L.LOCATION_ID
-- JOIN CRIME_PERSON CP ON C.CRIME_ID = CP.fk2_CRIME_ID
-- JOIN PERSON P ON CP.fk1_PERSON_ID = P.PERSON_ID
-- LEFT JOIN CRIME_EVIDENCE CE ON C.CRIME_ID = CE.fk2_CRIME_ID
-- LEFT JOIN EVIDENCE E ON CE.fk1_EVIDENCE_ID = E.EVIDENCE_ID;  

SELECT * FROM Crime_Details_View;