--Batch Updating For Crime Table
DROP TABLE CRIME_DETAILS CASCADE CONSTRAINTS;
CREATE TABLE CRIME_DETAILS AS (SELECT * FROM CRIME);
SELECT * FROM CRIME_DETAILS;

--Batch Updating for Location Table
DROP TABLE LOCATION_DETAILS CASCADE CONSTRAINTS;
CREATE TABLE LOCATION_DETAILS AS (SELECT * FROM LOCATION);
SELECT * FROM LOCATION_DETAILS;